# fly.toml app configuration file generated for phone-backend-rough-pond-7964 on 2024-07-04T04:01:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phone-backend-rough-pond-7964'
primary_region = 'mad'

[env]
  PORT = "3001"

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
